### ISSUE TITLE
Исправить тесты

### ISSUE THREAD

**Issue by php-coder** [AleksSPb/Spring-demo-App1#2]
Т.к. вы создали проект с помощью IDEA, то получили неработающие тесты из коробки :) Исправьте их, пожалуйста:

```
Spring-demo-App1 > mvn clean test
...
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.2 sec <<< FAILURE!
simple(com.springapp.mvc.AppTests)  Time elapsed: 0.004 sec  <<< ERROR!
java.lang.NoClassDefFoundError: javax/servlet/SessionCookieConfig
        at org.springframework.test.context.web.AbstractGenericWebContextLoader.configureWebResources(AbstractGenericWebContextLoader.java:199)
        at org.springframework.test.context.web.AbstractGenericWebContextLoader.loadContext(AbstractGenericWebContextLoader.java:126)
        at org.springframework.test.context.web.AbstractGenericWebContextLoader.loadContext(AbstractGenericWebContextLoader.java:59)
        at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.delegateLoading(AbstractDelegatingSmartContextLoader.java:108)
        at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.loadContext(AbstractDelegatingSmartContextLoader.java:260)
        at org.springframework.test.context.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:63)
        at org.springframework.test.context.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:83)
        at org.springframework.test.context.DefaultTestContext.getApplicationContext(DefaultTestContext.java:74)
        at org.springframework.test.context.web.ServletTestExecutionListener.setUpRequestContextIfNecessary(ServletTestExecutionListener.java:169)
        at org.springframework.test.context.web.ServletTestExecutionListener.prepareTestInstance(ServletTestExecutionListener.java:109)
        at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:212)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:199)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:251)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:253)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:216)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:82)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:60)
        at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:67)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:162)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.ClassNotFoundException: javax.servlet.SessionCookieConfig
        at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 38 more


Results :

Tests in error:
  simple(com.springapp.mvc.AppTests): javax/servlet/SessionCookieConfig

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.690 s
[INFO] Finished at: 2015-09-07T21:06:44+04:00
[INFO] Final Memory: 13M/314M
[INFO] ------------------------------------------------------------------------
```

**Comment by php-coder** [comment]
Подсказка -- дело в версии сервлетов (нужно обновиться с 2.5 до 3+)

**Comment by AleksSPb** [comment]
версии <groupId>javax.servlet</groupId>

<artifactId>javax.servlet-api</artifactId>
<version>3.1.0</version>

поставил

2015-09-07 22:10 GMT+03:00 Slava Semushin notifications@github.com:

> Подсказка -- дело в версии сервлетов (нужно обновиться с 2.5 до 3+)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/AleksSPb/Spring-demo-App1/issues/2#issuecomment-138361672
> .

## 

Всего наилучшего, Пархоменко Александр

**Comment by AleksSPb** [comment]
запушил

7 сентября 2015 г., 22:12 пользователь Александр Пархоменко <
paraleksi@gmail.com> написал:

> версии <groupId>javax.servlet</groupId>
> 
> <artifactId>javax.servlet-api</artifactId>
> <version>3.1.0</version>
> 
> поставил
> 
> 2015-09-07 22:10 GMT+03:00 Slava Semushin notifications@github.com:
> 
> > Подсказка -- дело в версии сервлетов (нужно обновиться с 2.5 до 3+)
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/AleksSPb/Spring-demo-App1/issues/2#issuecomment-138361672
> > .
> 
> ## 
> 
> Всего наилучшего, Пархоменко Александр

## 

Всего наилучшего, Пархоменко Александр

**Comment by php-coder** [comment]
Вижу, но не в той ветке. Перенесете в мастер?

**Comment by AleksSPb** [comment]
Попробую перенести. :)
IDEA пишет, что тесты пройдены, но если смотреть в лог...
То похоже что ничего не проверяется.
